name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y check

      - name: Build tests
        run: make tests

      - name: Run tests
        run: make check-unit

  regress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PostgreSQL apt repository
        run: |
          sudo apt install curl ca-certificates
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt purge postgresql-*
          sudo apt install -y postgresql-17 postgresql-server-dev-17

      - name: Build extension
        run: make

      - name: Install extension
        run: sudo make install

      - name: Configure PostgreSQL
        run: |
          echo "local all postgres trust" | sudo tee /etc/postgresql/17/main/pg_hba.conf

      - name: Start PostgreSQL
        run: |
          sudo systemctl stop postgresql
          sudo pg_ctlcluster 17 main start

      - name: Run tests
        run: PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)

